name: Release

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Update package.json version
      run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

    - name: Build
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Commit and push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'github-action-bot@github.com'
        git commit -am "Update version to ${{ github.event.release.tag_name }}"
        git push

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



        